# 复制它，改成settings.yml

account: 123456789 # 你的bot账号，qq则为qq号，tg则为taken
uin: 123456789 # 对于qq，是qq号；对于tg，是tg用户名
password: yourpassword # qq密码，如果tg或者二维码可以乱填
QRCode: false # 设为true则二维码登录（增加封号风险）

proxy: true
proxy_address: "http://127.0.0.1:10809"
# 对于tg的代理设置


mod: qq # 可选qq, telegram, test。

bot_owner: 114514 # 作为bot拥有者的你的账号

senioria: 1234567 # 是seni的账号（x


whitelist: true # 白名单还是黑名单

whitelist_groups: # 白名单
  - 114514 # 群1
  - 1919810 # 群2

blacklist_groups: #黑名单群
  - 19260917 # 群3

testing: false # 设为true的时候一定不写数据库。